<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260617000100 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Initial Asadero BAME API schema for Supabase PostgreSQL';
    }

    public function up(Schema $schema): void
    {
        $this->addSql("CREATE TABLE users (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(120) NOT NULL, surname VARCHAR(120) DEFAULT '' NOT NULL, email VARCHAR(180) NOT NULL, username VARCHAR(80) DEFAULT NULL, phone VARCHAR(40) DEFAULT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE UNIQUE INDEX UNIQ_USERS_EMAIL ON users (email)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_USERS_USERNAME ON users (username)');

        $this->addSql('CREATE TABLE categories (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(160) NOT NULL, slug VARCHAR(180) NOT NULL, description TEXT DEFAULT NULL, image_url VARCHAR(500) DEFAULT NULL, active BOOLEAN DEFAULT true NOT NULL, sort_order INT DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CATEGORIES_SLUG ON categories (slug)');
        $this->addSql('CREATE INDEX IDX_CATEGORIES_ACTIVE_SORT ON categories (active, sort_order)');

        $this->addSql('CREATE TABLE allergens (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(160) NOT NULL, slug VARCHAR(180) NOT NULL, description TEXT DEFAULT NULL, icon_url VARCHAR(500) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ALLERGENS_SLUG ON allergens (slug)');

        $this->addSql("CREATE TABLE products (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, category_id BIGINT NOT NULL, name VARCHAR(180) NOT NULL, slug VARCHAR(200) NOT NULL, description TEXT DEFAULT NULL, price NUMERIC(10, 2) NOT NULL, available BOOLEAN DEFAULT true NOT NULL, availability VARCHAR(40) DEFAULT 'available' NOT NULL, featured BOOLEAN DEFAULT false NOT NULL, weight VARCHAR(80) DEFAULT NULL, prep_time SMALLINT DEFAULT NULL, image_path VARCHAR(500) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PRODUCTS_SLUG ON products (slug)');
        $this->addSql('CREATE INDEX IDX_PRODUCTS_CATEGORY ON products (category_id)');
        $this->addSql('CREATE INDEX IDX_PRODUCTS_AVAILABILITY ON products (available, availability)');
        $this->addSql('CREATE INDEX IDX_PRODUCTS_FEATURED ON products (featured)');
        $this->addSql("ALTER TABLE products ADD CONSTRAINT FK_PRODUCTS_CATEGORY FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE");
        $this->addSql("ALTER TABLE products ADD CONSTRAINT CHK_PRODUCTS_PRICE CHECK (price >= 0)");
        $this->addSql("ALTER TABLE products ADD CONSTRAINT CHK_PRODUCTS_AVAILABILITY CHECK (availability IN ('available', 'low_stock', 'sold_out', 'hidden'))");

        $this->addSql('CREATE TABLE product_allergen (product_id BIGINT NOT NULL, allergen_id BIGINT NOT NULL, PRIMARY KEY(product_id, allergen_id))');
        $this->addSql('CREATE INDEX IDX_PRODUCT_ALLERGEN_PRODUCT ON product_allergen (product_id)');
        $this->addSql('CREATE INDEX IDX_PRODUCT_ALLERGEN_ALLERGEN ON product_allergen (allergen_id)');
        $this->addSql('ALTER TABLE product_allergen ADD CONSTRAINT FK_PRODUCT_ALLERGEN_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE product_allergen ADD CONSTRAINT FK_PRODUCT_ALLERGEN_ALLERGEN FOREIGN KEY (allergen_id) REFERENCES allergens (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql("CREATE TABLE locals (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(180) NOT NULL, address VARCHAR(255) NOT NULL, city VARCHAR(120) DEFAULT 'Murcia' NOT NULL, postal_code VARCHAR(20) DEFAULT NULL, phone VARCHAR(40) NOT NULL, email VARCHAR(180) DEFAULT NULL, latitude NUMERIC(10, 7) DEFAULT NULL, longitude NUMERIC(10, 7) DEFAULT NULL, hours JSON NOT NULL, active BOOLEAN DEFAULT true NOT NULL, status VARCHAR(40) DEFAULT 'open' NOT NULL, whatsapp VARCHAR(40) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE INDEX IDX_LOCALS_STATUS ON locals (status)');
        $this->addSql('CREATE INDEX IDX_LOCALS_ACTIVE_STATUS ON locals (active, status)');
        $this->addSql("ALTER TABLE locals ADD CONSTRAINT CHK_LOCALS_STATUS CHECK (status IN ('open', 'closed', 'closing_soon', 'temporarily_closed'))");

        $this->addSql('CREATE TABLE local_product (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, local_id BIGINT NOT NULL, product_id BIGINT NOT NULL, stock INT DEFAULT 0 NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_LOCAL_PRODUCT ON local_product (local_id, product_id)');
        $this->addSql('CREATE INDEX IDX_LOCAL_PRODUCT_LOCAL ON local_product (local_id)');
        $this->addSql('CREATE INDEX IDX_LOCAL_PRODUCT_PRODUCT ON local_product (product_id)');
        $this->addSql('ALTER TABLE local_product ADD CONSTRAINT FK_LOCAL_PRODUCT_LOCAL FOREIGN KEY (local_id) REFERENCES locals (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE local_product ADD CONSTRAINT FK_LOCAL_PRODUCT_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE local_product ADD CONSTRAINT CHK_LOCAL_PRODUCT_STOCK CHECK (stock >= 0)');

        $this->addSql("CREATE TABLE orders (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id BIGINT NOT NULL, local_id BIGINT DEFAULT NULL, reference VARCHAR(40) NOT NULL, status VARCHAR(40) DEFAULT 'pending' NOT NULL, type VARCHAR(40) DEFAULT 'takeaway' NOT NULL, total NUMERIC(10, 2) DEFAULT '0.00' NOT NULL, notes TEXT DEFAULT NULL, estimated_time SMALLINT DEFAULT NULL, phone VARCHAR(40) DEFAULT NULL, address VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))");
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ORDERS_REFERENCE ON orders (reference)');
        $this->addSql('CREATE INDEX IDX_ORDERS_USER ON orders (user_id)');
        $this->addSql('CREATE INDEX IDX_ORDERS_LOCAL ON orders (local_id)');
        $this->addSql('CREATE INDEX IDX_ORDERS_STATUS ON orders (status)');
        $this->addSql('CREATE INDEX IDX_ORDERS_CREATED_AT ON orders (created_at)');
        $this->addSql('ALTER TABLE orders ADD CONSTRAINT FK_ORDERS_USER FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE orders ADD CONSTRAINT FK_ORDERS_LOCAL FOREIGN KEY (local_id) REFERENCES locals (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql("ALTER TABLE orders ADD CONSTRAINT CHK_ORDERS_STATUS CHECK (status IN ('pending', 'confirmed', 'preparing', 'ready', 'completed', 'cancelled'))");
        $this->addSql("ALTER TABLE orders ADD CONSTRAINT CHK_ORDERS_TYPE CHECK (type IN ('takeaway', 'delivery'))");
        $this->addSql('ALTER TABLE orders ADD CONSTRAINT CHK_ORDERS_TOTAL CHECK (total >= 0)');

        $this->addSql('CREATE TABLE order_lines (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, order_id BIGINT NOT NULL, product_id BIGINT NOT NULL, quantity INT NOT NULL, unit_price NUMERIC(10, 2) NOT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_ORDER_LINES_ORDER ON order_lines (order_id)');
        $this->addSql('CREATE INDEX IDX_ORDER_LINES_PRODUCT ON order_lines (product_id)');
        $this->addSql('ALTER TABLE order_lines ADD CONSTRAINT FK_ORDER_LINES_ORDER FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE order_lines ADD CONSTRAINT FK_ORDER_LINES_PRODUCT FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE RESTRICT NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE order_lines ADD CONSTRAINT CHK_ORDER_LINES_QUANTITY CHECK (quantity >= 1)');
        $this->addSql('ALTER TABLE order_lines ADD CONSTRAINT CHK_ORDER_LINES_UNIT_PRICE CHECK (unit_price >= 0)');

        $this->addSql('CREATE TABLE personal_access_tokens (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id BIGINT NOT NULL, token_hash VARCHAR(64) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, revoked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PERSONAL_ACCESS_TOKEN_HASH ON personal_access_tokens (token_hash)');
        $this->addSql('CREATE INDEX IDX_PERSONAL_ACCESS_TOKEN_USER ON personal_access_tokens (user_id)');
        $this->addSql('ALTER TABLE personal_access_tokens ADD CONSTRAINT FK_PERSONAL_ACCESS_TOKEN_USER FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE password_reset_tokens (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id BIGINT NOT NULL, token_hash VARCHAR(64) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, used_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PASSWORD_RESET_TOKEN_HASH ON password_reset_tokens (token_hash)');
        $this->addSql('CREATE INDEX IDX_PASSWORD_RESET_TOKEN_USER ON password_reset_tokens (user_id)');
        $this->addSql('ALTER TABLE password_reset_tokens ADD CONSTRAINT FK_PASSWORD_RESET_TOKEN_USER FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS password_reset_tokens');
        $this->addSql('DROP TABLE IF EXISTS personal_access_tokens');
        $this->addSql('DROP TABLE IF EXISTS order_lines');
        $this->addSql('DROP TABLE IF EXISTS orders');
        $this->addSql('DROP TABLE IF EXISTS local_product');
        $this->addSql('DROP TABLE IF EXISTS locals');
        $this->addSql('DROP TABLE IF EXISTS product_allergen');
        $this->addSql('DROP TABLE IF EXISTS products');
        $this->addSql('DROP TABLE IF EXISTS allergens');
        $this->addSql('DROP TABLE IF EXISTS categories');
        $this->addSql('DROP TABLE IF EXISTS users');
    }
}
